# Generated by Django 3.2.20 on 2023-10-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('pre-owned', 'pre-owned')], default='new', max_length=50),
        ),
    ]
