# Generated by Django 3.2.20 on 2023-10-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
