# Generated by Django 3.2.20 on 2023-10-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auctionbid_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transcation_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='total amount for the product', max_digits=10)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
