# Generated by Django 3.2.20 on 2023-10-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='acution',
            field=models.CharField(default='k', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='phonenumber',
            field=models.CharField(default='k', max_length=50),
        ),
    ]
