# Generated by Django 3.2.22 on 2023-10-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231012_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='acution',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phonenumber',
            field=models.CharField(max_length=50),
        ),
    ]
