# Generated by Django 3.2.22 on 2023-10-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231027_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='proxy_item_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
